# GitHub Sponsors configuration
# Remove or modify this file based on your funding preferences

# github: RahulPatnaik
# patreon: your-patreon-username
# ko_fi: your-kofi-username
# custom: ['https://your-website.com/donate']
